version: '3.4'

services:
  ntp:
    image: mcchae/ntp-server   # TODO: 
    #image: cturra/ntp
    container_name: ntp_server
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    # tcpdump -i any -nn udp
  ntptest:
    image: ubuntu
    container_name: ntp_client
    links:
      - ntp
    command: /bin/sleep 1000
    # apt update && apt install -y iputils-ping ntpdate
    # ntpdate -q -o 2 -dv -p 1 -t 1 ntp
